-- Initial schema generated by Prisma 7.10.0, followed by reviewed PostgreSQL-only constraints.
-- pgvector must be available on the database server before this migration is applied.
BEGIN;
CREATE EXTENSION IF NOT EXISTS vector;

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "AccountType" AS ENUM ('INDIVIDUAL', 'AGENCY', 'FREELANCE');

-- CreateEnum
CREATE TYPE "TeamRole" AS ENUM ('OWNER', 'ADMIN', 'EDITOR', 'REVIEWER', 'PUBLISHER', 'VIEWER');

-- CreateEnum
CREATE TYPE "IdentityProvider" AS ENUM ('GOOGLE');

-- CreateEnum
CREATE TYPE "InvitationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "Marketplace" AS ENUM ('AMAZON', 'FLIPKART');

-- CreateEnum
CREATE TYPE "ConnectionStatus" AS ENUM ('NOT_CONNECTED', 'CONNECTED', 'EXPIRED', 'REVOKED', 'ERROR');

-- CreateEnum
CREATE TYPE "ListingStatus" AS ENUM ('DRAFT', 'REVIEW_PENDING', 'READY', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "PublicationStatus" AS ENUM ('NEVER_PUBLISHED', 'PENDING', 'LIVE', 'REJECTED', 'INACTIVE');

-- CreateEnum
CREATE TYPE "JobStatus" AS ENUM ('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ValidationStatus" AS ENUM ('PENDING', 'PASSED', 'FAILED', 'ERROR');

-- CreateEnum
CREATE TYPE "PublishRoute" AS ENUM ('FLAT_FILE_CSV', 'DIRECT_API');

-- CreateEnum
CREATE TYPE "PublishStatus" AS ENUM ('QUEUED', 'PROCESSING', 'EXPORT_READY', 'SUBMITTED', 'PUBLISHED', 'FAILED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "AssetKind" AS ENUM ('IMAGE', 'VIDEO', 'CSV', 'DOCUMENT');

-- CreateEnum
CREATE TYPE "MediaRole" AS ENUM ('MAIN_IMAGE', 'GALLERY_IMAGE', 'SWATCH_IMAGE', 'VIDEO');

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL,
    "email" VARCHAR(320) NOT NULL,
    "display_name" VARCHAR(255) NOT NULL,
    "password_hash" TEXT,
    "account_type" "AccountType" NOT NULL DEFAULT 'INDIVIDUAL',
    "email_verified_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "auth_identities" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "provider" "IdentityProvider" NOT NULL,
    "subject" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_identities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "teams" (
    "id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "teams_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "team_memberships" (
    "team_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "role" "TeamRole" NOT NULL DEFAULT 'VIEWER',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "team_memberships_pkey" PRIMARY KEY ("team_id","user_id")
);

-- CreateTable
CREATE TABLE "invitations" (
    "id" UUID NOT NULL,
    "team_id" UUID NOT NULL,
    "inviter_id" UUID NOT NULL,
    "email" VARCHAR(320) NOT NULL,
    "role" "TeamRole" NOT NULL DEFAULT 'EDITOR',
    "token_hash" VARCHAR(128) NOT NULL,
    "status" "InvitationStatus" NOT NULL DEFAULT 'PENDING',
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "accepted_at" TIMESTAMPTZ(3),
    "accepted_by_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "folders" (
    "id" UUID NOT NULL,
    "team_id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "folders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "workspaces" (
    "id" UUID NOT NULL,
    "team_id" UUID NOT NULL,
    "folder_id" UUID,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "archived_at" TIMESTAMPTZ(3),

    CONSTRAINT "workspaces_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "brand_contexts" (
    "id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "tone" VARCHAR(120) NOT NULL DEFAULT 'Professional & clear',
    "glossary" JSONB NOT NULL DEFAULT '{}',
    "banned_terms" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "pain_points" TEXT,
    "embedding" vector(1536),
    "embedding_model" VARCHAR(120),
    "embedded_at" TIMESTAMPTZ(3),
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "brand_contexts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "marketplace_connections" (
    "id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "platform" "Marketplace" NOT NULL,
    "seller_id" VARCHAR(255) NOT NULL,
    "label" VARCHAR(255),
    "status" "ConnectionStatus" NOT NULL DEFAULT 'NOT_CONNECTED',
    "encrypted_access_token" TEXT,
    "encrypted_refresh_token" TEXT,
    "token_expires_at" TIMESTAMPTZ(3),
    "scopes" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "marketplace_connections_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "products" (
    "id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "brand_context_id" UUID NOT NULL,
    "import_batch_id" UUID,
    "name" VARCHAR(500) NOT NULL,
    "category_path" TEXT,
    "raw_input_text" TEXT,
    "canonical_data" JSONB NOT NULL DEFAULT '{}',
    "attributes" JSONB NOT NULL DEFAULT '{}',
    "description_template" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "products_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_variants" (
    "id" UUID NOT NULL,
    "product_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "seller_sku" VARCHAR(100) NOT NULL,
    "name" VARCHAR(255),
    "color" VARCHAR(120),
    "size" VARCHAR(120),
    "attributes" JSONB NOT NULL DEFAULT '{}',
    "currency" CHAR(3) NOT NULL DEFAULT 'INR',
    "mrp" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "selling_price" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "hsn_code" VARCHAR(16),
    "country_of_origin" VARCHAR(120),
    "weight_kg" DECIMAL(10,3),
    "length_cm" DECIMAL(10,3),
    "breadth_cm" DECIMAL(10,3),
    "height_cm" DECIMAL(10,3),
    "tax_code" VARCHAR(80),
    "manufacturer_details" TEXT,
    "packer_details" TEXT,
    "importer_details" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "product_variants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "marketplace_listings" (
    "id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "variant_id" UUID NOT NULL,
    "connection_id" UUID,
    "platform" "Marketplace" NOT NULL,
    "marketplace_region" VARCHAR(40) NOT NULL DEFAULT 'IN',
    "external_id" VARCHAR(255),
    "product_url" TEXT,
    "status" "ListingStatus" NOT NULL DEFAULT 'DRAFT',
    "publication_status" "PublicationStatus" NOT NULL DEFAULT 'NEVER_PUBLISHED',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "marketplace_listings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "listing_revisions" (
    "id" UUID NOT NULL,
    "listing_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "number" INTEGER NOT NULL,
    "created_by_id" UUID,
    "generation_job_id" UUID,
    "title" TEXT NOT NULL DEFAULT '',
    "description" TEXT NOT NULL DEFAULT '',
    "bullet_points" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "search_keywords" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "target_keywords" JSONB NOT NULL DEFAULT '[]',
    "aplus_content" JSONB NOT NULL DEFAULT '{}',
    "merchant_snapshot" JSONB NOT NULL DEFAULT '{}',
    "brand_context_snapshot" JSONB NOT NULL DEFAULT '{}',
    "generation_metadata" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "listing_revisions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "marketplace_payloads" (
    "id" UUID NOT NULL,
    "revision_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "category_code" VARCHAR(255),
    "template_version" VARCHAR(120),
    "raw_attributes" JSONB NOT NULL DEFAULT '{}',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "marketplace_payloads_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "generation_jobs" (
    "id" UUID NOT NULL,
    "listing_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "requested_by_id" UUID,
    "queue_job_id" VARCHAR(255),
    "status" "JobStatus" NOT NULL DEFAULT 'QUEUED',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "max_attempts" INTEGER NOT NULL DEFAULT 3,
    "input_snapshot" JSONB NOT NULL DEFAULT '{}',
    "error_report" JSONB,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMPTZ(3),
    "completed_at" TIMESTAMPTZ(3),

    CONSTRAINT "generation_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "validation_runs" (
    "id" UUID NOT NULL,
    "revision_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "status" "ValidationStatus" NOT NULL DEFAULT 'PENDING',
    "ruleset_version" VARCHAR(120) NOT NULL,
    "score" INTEGER,
    "errors" JSONB NOT NULL DEFAULT '[]',
    "warnings" JSONB NOT NULL DEFAULT '[]',
    "auto_fix_applied" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(3),

    CONSTRAINT "validation_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "listing_approvals" (
    "id" UUID NOT NULL,
    "revision_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "validation_run_id" UUID NOT NULL,
    "approved_by_id" UUID NOT NULL,
    "approved_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "revoked_at" TIMESTAMPTZ(3),
    "revocation_reason" TEXT,

    CONSTRAINT "listing_approvals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "publish_jobs" (
    "id" UUID NOT NULL,
    "listing_id" UUID NOT NULL,
    "platform" "Marketplace" NOT NULL,
    "connection_id" UUID,
    "revision_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "approval_id" UUID NOT NULL,
    "route" "PublishRoute" NOT NULL,
    "status" "PublishStatus" NOT NULL DEFAULT 'QUEUED',
    "idempotency_key" VARCHAR(255) NOT NULL,
    "submission_id" VARCHAR(255),
    "export_asset_id" UUID,
    "target_snapshot" JSONB NOT NULL DEFAULT '{}',
    "response_payload" JSONB NOT NULL DEFAULT '{}',
    "error_report" JSONB,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "started_at" TIMESTAMPTZ(3),
    "submitted_at" TIMESTAMPTZ(3),
    "completed_at" TIMESTAMPTZ(3),
    "published_at" TIMESTAMPTZ(3),

    CONSTRAINT "publish_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "media_assets" (
    "id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "uploaded_by_id" UUID,
    "kind" "AssetKind" NOT NULL,
    "storage_key" TEXT NOT NULL,
    "original_name" VARCHAR(255) NOT NULL,
    "mime_type" VARCHAR(120) NOT NULL,
    "size_bytes" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(3),

    CONSTRAINT "media_assets_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product_media" (
    "id" UUID NOT NULL,
    "product_id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "variant_id" UUID,
    "asset_id" UUID NOT NULL,
    "role" "MediaRole" NOT NULL DEFAULT 'GALLERY_IMAGE',
    "position" INTEGER NOT NULL DEFAULT 0,
    "alt_text" VARCHAR(500),

    CONSTRAINT "product_media_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "import_batches" (
    "id" UUID NOT NULL,
    "workspace_id" UUID NOT NULL,
    "source_asset_id" UUID NOT NULL,
    "requested_by_id" UUID,
    "status" "JobStatus" NOT NULL DEFAULT 'QUEUED',
    "queue_job_id" VARCHAR(255),
    "total_rows" INTEGER NOT NULL DEFAULT 0,
    "imported_rows" INTEGER NOT NULL DEFAULT 0,
    "failed_rows" INTEGER NOT NULL DEFAULT 0,
    "error_report" JSONB NOT NULL DEFAULT '[]',
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMPTZ(3),

    CONSTRAINT "import_batches_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE INDEX "auth_identities_user_id_idx" ON "auth_identities"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "auth_identities_provider_subject_key" ON "auth_identities"("provider", "subject");

-- CreateIndex
CREATE INDEX "teams_created_by_id_idx" ON "teams"("created_by_id");

-- CreateIndex
CREATE INDEX "team_memberships_user_id_idx" ON "team_memberships"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "invitations_token_hash_key" ON "invitations"("token_hash");

-- CreateIndex
CREATE INDEX "invitations_team_id_email_status_idx" ON "invitations"("team_id", "email", "status");

-- CreateIndex
CREATE INDEX "invitations_inviter_id_idx" ON "invitations"("inviter_id");

-- CreateIndex
CREATE INDEX "invitations_accepted_by_id_idx" ON "invitations"("accepted_by_id");

-- CreateIndex
CREATE INDEX "invitations_status_expires_at_idx" ON "invitations"("status", "expires_at");

-- CreateIndex
CREATE UNIQUE INDEX "folders_id_team_id_key" ON "folders"("id", "team_id");

-- CreateIndex
CREATE UNIQUE INDEX "folders_team_id_name_key" ON "folders"("team_id", "name");

-- CreateIndex
CREATE INDEX "workspaces_team_id_archived_at_idx" ON "workspaces"("team_id", "archived_at");

-- CreateIndex
CREATE INDEX "workspaces_folder_id_team_id_idx" ON "workspaces"("folder_id", "team_id");

-- CreateIndex
CREATE UNIQUE INDEX "brand_contexts_workspace_id_key" ON "brand_contexts"("workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "brand_contexts_id_workspace_id_key" ON "brand_contexts"("id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "marketplace_connections_workspace_id_platform_seller_id_key" ON "marketplace_connections"("workspace_id", "platform", "seller_id");

-- CreateIndex
CREATE UNIQUE INDEX "marketplace_connections_id_workspace_id_platform_key" ON "marketplace_connections"("id", "workspace_id", "platform");

-- CreateIndex
CREATE INDEX "products_workspace_id_deleted_at_created_at_idx" ON "products"("workspace_id", "deleted_at", "created_at");

-- CreateIndex
CREATE INDEX "products_brand_context_id_workspace_id_idx" ON "products"("brand_context_id", "workspace_id");

-- CreateIndex
CREATE INDEX "products_import_batch_id_workspace_id_idx" ON "products"("import_batch_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "products_id_workspace_id_key" ON "products"("id", "workspace_id");

-- CreateIndex
CREATE INDEX "product_variants_product_id_workspace_id_deleted_at_idx" ON "product_variants"("product_id", "workspace_id", "deleted_at");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_workspace_id_seller_sku_key" ON "product_variants"("workspace_id", "seller_sku");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_id_workspace_id_key" ON "product_variants"("id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "product_variants_id_product_id_workspace_id_key" ON "product_variants"("id", "product_id", "workspace_id");

-- CreateIndex
CREATE INDEX "marketplace_listings_workspace_id_status_updated_at_idx" ON "marketplace_listings"("workspace_id", "status", "updated_at");

-- CreateIndex
CREATE INDEX "marketplace_listings_workspace_id_platform_publication_stat_idx" ON "marketplace_listings"("workspace_id", "platform", "publication_status");

-- CreateIndex
CREATE INDEX "marketplace_listings_connection_id_workspace_id_platform_idx" ON "marketplace_listings"("connection_id", "workspace_id", "platform");

-- CreateIndex
CREATE INDEX "marketplace_listings_variant_id_workspace_id_idx" ON "marketplace_listings"("variant_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "marketplace_listings_id_workspace_id_platform_key" ON "marketplace_listings"("id", "workspace_id", "platform");

-- CreateIndex
CREATE UNIQUE INDEX "marketplace_listings_variant_id_platform_marketplace_region_key" ON "marketplace_listings"("variant_id", "platform", "marketplace_region");

-- CreateIndex
CREATE UNIQUE INDEX "marketplace_listings_id_workspace_id_key" ON "marketplace_listings"("id", "workspace_id");

-- CreateIndex
CREATE INDEX "listing_revisions_listing_id_workspace_id_idx" ON "listing_revisions"("listing_id", "workspace_id");

-- CreateIndex
CREATE INDEX "listing_revisions_created_by_id_idx" ON "listing_revisions"("created_by_id");

-- CreateIndex
CREATE INDEX "listing_revisions_generation_job_id_listing_id_workspace_id_idx" ON "listing_revisions"("generation_job_id", "listing_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "listing_revisions_listing_id_number_key" ON "listing_revisions"("listing_id", "number");

-- CreateIndex
CREATE UNIQUE INDEX "listing_revisions_id_listing_id_workspace_id_key" ON "listing_revisions"("id", "listing_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "listing_revisions_id_workspace_id_key" ON "listing_revisions"("id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "marketplace_payloads_revision_id_key" ON "marketplace_payloads"("revision_id");

-- CreateIndex
CREATE UNIQUE INDEX "marketplace_payloads_revision_id_workspace_id_key" ON "marketplace_payloads"("revision_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "generation_jobs_queue_job_id_key" ON "generation_jobs"("queue_job_id");

-- CreateIndex
CREATE INDEX "generation_jobs_listing_id_workspace_id_idx" ON "generation_jobs"("listing_id", "workspace_id");

-- CreateIndex
CREATE INDEX "generation_jobs_workspace_id_status_created_at_idx" ON "generation_jobs"("workspace_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "generation_jobs_requested_by_id_idx" ON "generation_jobs"("requested_by_id");

-- CreateIndex
CREATE UNIQUE INDEX "generation_jobs_id_listing_id_workspace_id_key" ON "generation_jobs"("id", "listing_id", "workspace_id");

-- CreateIndex
CREATE INDEX "validation_runs_revision_id_workspace_id_created_at_idx" ON "validation_runs"("revision_id", "workspace_id", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "validation_runs_id_revision_id_workspace_id_key" ON "validation_runs"("id", "revision_id", "workspace_id");

-- CreateIndex
CREATE INDEX "listing_approvals_revision_id_workspace_id_idx" ON "listing_approvals"("revision_id", "workspace_id");

-- CreateIndex
CREATE INDEX "listing_approvals_validation_run_id_revision_id_workspace_i_idx" ON "listing_approvals"("validation_run_id", "revision_id", "workspace_id");

-- CreateIndex
CREATE INDEX "listing_approvals_approved_by_id_idx" ON "listing_approvals"("approved_by_id");

-- CreateIndex
CREATE UNIQUE INDEX "listing_approvals_id_revision_id_workspace_id_key" ON "listing_approvals"("id", "revision_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "publish_jobs_idempotency_key_key" ON "publish_jobs"("idempotency_key");

-- CreateIndex
CREATE INDEX "publish_jobs_revision_id_listing_id_workspace_id_idx" ON "publish_jobs"("revision_id", "listing_id", "workspace_id");

-- CreateIndex
CREATE INDEX "publish_jobs_listing_id_workspace_id_platform_idx" ON "publish_jobs"("listing_id", "workspace_id", "platform");

-- CreateIndex
CREATE INDEX "publish_jobs_connection_id_workspace_id_platform_idx" ON "publish_jobs"("connection_id", "workspace_id", "platform");

-- CreateIndex
CREATE INDEX "publish_jobs_approval_id_revision_id_workspace_id_idx" ON "publish_jobs"("approval_id", "revision_id", "workspace_id");

-- CreateIndex
CREATE INDEX "publish_jobs_export_asset_id_workspace_id_idx" ON "publish_jobs"("export_asset_id", "workspace_id");

-- CreateIndex
CREATE INDEX "publish_jobs_workspace_id_status_created_at_idx" ON "publish_jobs"("workspace_id", "status", "created_at");

-- CreateIndex
CREATE UNIQUE INDEX "media_assets_storage_key_key" ON "media_assets"("storage_key");

-- CreateIndex
CREATE INDEX "media_assets_workspace_id_kind_created_at_idx" ON "media_assets"("workspace_id", "kind", "created_at");

-- CreateIndex
CREATE INDEX "media_assets_uploaded_by_id_idx" ON "media_assets"("uploaded_by_id");

-- CreateIndex
CREATE UNIQUE INDEX "media_assets_id_workspace_id_key" ON "media_assets"("id", "workspace_id");

-- CreateIndex
CREATE INDEX "product_media_product_id_workspace_id_position_idx" ON "product_media"("product_id", "workspace_id", "position");

-- CreateIndex
CREATE INDEX "product_media_variant_id_product_id_workspace_id_idx" ON "product_media"("variant_id", "product_id", "workspace_id");

-- CreateIndex
CREATE INDEX "product_media_asset_id_workspace_id_idx" ON "product_media"("asset_id", "workspace_id");

-- CreateIndex
CREATE UNIQUE INDEX "import_batches_queue_job_id_key" ON "import_batches"("queue_job_id");

-- CreateIndex
CREATE INDEX "import_batches_workspace_id_status_created_at_idx" ON "import_batches"("workspace_id", "status", "created_at");

-- CreateIndex
CREATE INDEX "import_batches_source_asset_id_workspace_id_idx" ON "import_batches"("source_asset_id", "workspace_id");

-- CreateIndex
CREATE INDEX "import_batches_requested_by_id_idx" ON "import_batches"("requested_by_id");

-- CreateIndex
CREATE UNIQUE INDEX "import_batches_id_workspace_id_key" ON "import_batches"("id", "workspace_id");

-- AddForeignKey
ALTER TABLE "auth_identities" ADD CONSTRAINT "auth_identities_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "teams" ADD CONSTRAINT "teams_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_memberships" ADD CONSTRAINT "team_memberships_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "team_memberships" ADD CONSTRAINT "team_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_inviter_id_fkey" FOREIGN KEY ("inviter_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_accepted_by_id_fkey" FOREIGN KEY ("accepted_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "folders" ADD CONSTRAINT "folders_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspaces" ADD CONSTRAINT "workspaces_team_id_fkey" FOREIGN KEY ("team_id") REFERENCES "teams"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "workspaces" ADD CONSTRAINT "workspaces_folder_id_team_id_fkey" FOREIGN KEY ("folder_id", "team_id") REFERENCES "folders"("id", "team_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "brand_contexts" ADD CONSTRAINT "brand_contexts_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "marketplace_connections" ADD CONSTRAINT "marketplace_connections_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_brand_context_id_workspace_id_fkey" FOREIGN KEY ("brand_context_id", "workspace_id") REFERENCES "brand_contexts"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "products" ADD CONSTRAINT "products_import_batch_id_workspace_id_fkey" FOREIGN KEY ("import_batch_id", "workspace_id") REFERENCES "import_batches"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "product_variants" ADD CONSTRAINT "product_variants_product_id_workspace_id_fkey" FOREIGN KEY ("product_id", "workspace_id") REFERENCES "products"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "marketplace_listings" ADD CONSTRAINT "marketplace_listings_variant_id_workspace_id_fkey" FOREIGN KEY ("variant_id", "workspace_id") REFERENCES "product_variants"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "marketplace_listings" ADD CONSTRAINT "marketplace_listings_connection_id_workspace_id_platform_fkey" FOREIGN KEY ("connection_id", "workspace_id", "platform") REFERENCES "marketplace_connections"("id", "workspace_id", "platform") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "listing_revisions" ADD CONSTRAINT "listing_revisions_listing_id_workspace_id_fkey" FOREIGN KEY ("listing_id", "workspace_id") REFERENCES "marketplace_listings"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "listing_revisions" ADD CONSTRAINT "listing_revisions_created_by_id_fkey" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "listing_revisions" ADD CONSTRAINT "listing_revisions_generation_job_id_listing_id_workspace_i_fkey" FOREIGN KEY ("generation_job_id", "listing_id", "workspace_id") REFERENCES "generation_jobs"("id", "listing_id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "marketplace_payloads" ADD CONSTRAINT "marketplace_payloads_revision_id_workspace_id_fkey" FOREIGN KEY ("revision_id", "workspace_id") REFERENCES "listing_revisions"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "generation_jobs" ADD CONSTRAINT "generation_jobs_listing_id_workspace_id_fkey" FOREIGN KEY ("listing_id", "workspace_id") REFERENCES "marketplace_listings"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "generation_jobs" ADD CONSTRAINT "generation_jobs_requested_by_id_fkey" FOREIGN KEY ("requested_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "validation_runs" ADD CONSTRAINT "validation_runs_revision_id_workspace_id_fkey" FOREIGN KEY ("revision_id", "workspace_id") REFERENCES "listing_revisions"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "listing_approvals" ADD CONSTRAINT "listing_approvals_revision_id_workspace_id_fkey" FOREIGN KEY ("revision_id", "workspace_id") REFERENCES "listing_revisions"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "listing_approvals" ADD CONSTRAINT "listing_approvals_validation_run_id_revision_id_workspace__fkey" FOREIGN KEY ("validation_run_id", "revision_id", "workspace_id") REFERENCES "validation_runs"("id", "revision_id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "listing_approvals" ADD CONSTRAINT "listing_approvals_approved_by_id_fkey" FOREIGN KEY ("approved_by_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "publish_jobs" ADD CONSTRAINT "publish_jobs_revision_id_listing_id_workspace_id_fkey" FOREIGN KEY ("revision_id", "listing_id", "workspace_id") REFERENCES "listing_revisions"("id", "listing_id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "publish_jobs" ADD CONSTRAINT "publish_jobs_listing_id_workspace_id_platform_fkey" FOREIGN KEY ("listing_id", "workspace_id", "platform") REFERENCES "marketplace_listings"("id", "workspace_id", "platform") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "publish_jobs" ADD CONSTRAINT "publish_jobs_connection_id_workspace_id_platform_fkey" FOREIGN KEY ("connection_id", "workspace_id", "platform") REFERENCES "marketplace_connections"("id", "workspace_id", "platform") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "publish_jobs" ADD CONSTRAINT "publish_jobs_approval_id_revision_id_workspace_id_fkey" FOREIGN KEY ("approval_id", "revision_id", "workspace_id") REFERENCES "listing_approvals"("id", "revision_id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "publish_jobs" ADD CONSTRAINT "publish_jobs_export_asset_id_workspace_id_fkey" FOREIGN KEY ("export_asset_id", "workspace_id") REFERENCES "media_assets"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "media_assets" ADD CONSTRAINT "media_assets_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "media_assets" ADD CONSTRAINT "media_assets_uploaded_by_id_fkey" FOREIGN KEY ("uploaded_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_product_id_workspace_id_fkey" FOREIGN KEY ("product_id", "workspace_id") REFERENCES "products"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_variant_id_product_id_workspace_id_fkey" FOREIGN KEY ("variant_id", "product_id", "workspace_id") REFERENCES "product_variants"("id", "product_id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "product_media" ADD CONSTRAINT "product_media_asset_id_workspace_id_fkey" FOREIGN KEY ("asset_id", "workspace_id") REFERENCES "media_assets"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_source_asset_id_workspace_id_fkey" FOREIGN KEY ("source_asset_id", "workspace_id") REFERENCES "media_assets"("id", "workspace_id") ON DELETE RESTRICT ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_requested_by_id_fkey" FOREIGN KEY ("requested_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Application invariants not expressible in Prisma Schema Language.
-- Keep these in migration history: `prisma db push` cannot reproduce this complete schema.
ALTER TABLE "users"
  ADD CONSTRAINT "users_email_normalized" CHECK (email = lower(btrim(email)) AND email <> ''),
  ADD CONSTRAINT "users_display_name_nonempty" CHECK (btrim(display_name) <> '');

ALTER TABLE "invitations"
  ADD CONSTRAINT "invitations_email_normalized" CHECK (email = lower(btrim(email)) AND email <> ''),
  ADD CONSTRAINT "invitations_expiry_valid" CHECK (expires_at > created_at),
  ADD CONSTRAINT "invitations_acceptance_timestamp" CHECK ((status = 'ACCEPTED') = (accepted_at IS NOT NULL));

CREATE UNIQUE INDEX "invitations_one_pending_per_team_email"
  ON "invitations" (team_id, email) WHERE status = 'PENDING';

ALTER TABLE "brand_contexts"
  ADD CONSTRAINT "brand_name_nonempty" CHECK (btrim(name) <> ''),
  ADD CONSTRAINT "brand_glossary_object" CHECK (jsonb_typeof(glossary) = 'object');

ALTER TABLE "products"
  ADD CONSTRAINT "products_name_nonempty" CHECK (btrim(name) <> ''),
  ADD CONSTRAINT "products_facts_objects" CHECK (
    jsonb_typeof(canonical_data) = 'object' AND jsonb_typeof(attributes) = 'object'
  );

-- Keep SKU identity reserved after soft deletion to avoid accidentally reusing external mappings.
CREATE UNIQUE INDEX "product_variants_workspace_sku_ci_key"
  ON "product_variants" (workspace_id, lower(seller_sku));
ALTER TABLE "product_variants"
  ADD CONSTRAINT "variant_sku_nonempty_trimmed" CHECK (seller_sku = btrim(seller_sku) AND seller_sku <> ''),
  ADD CONSTRAINT "variant_prices_valid" CHECK (
    mrp >= 0 AND mrp < 'Infinity'::numeric AND
    selling_price >= 0 AND selling_price < 'Infinity'::numeric AND selling_price <= mrp
  ),
  ADD CONSTRAINT "variant_stock_nonnegative" CHECK (stock >= 0),
  ADD CONSTRAINT "variant_currency_iso_shape" CHECK (currency ~ '^[A-Z]{3}$'),
  ADD CONSTRAINT "variant_attributes_object" CHECK (jsonb_typeof(attributes) = 'object'),
  ADD CONSTRAINT "variant_measurements_valid" CHECK (
    (weight_kg IS NULL OR (weight_kg >= 0 AND weight_kg < 'Infinity'::numeric)) AND
    (length_cm IS NULL OR (length_cm >= 0 AND length_cm < 'Infinity'::numeric)) AND
    (breadth_cm IS NULL OR (breadth_cm >= 0 AND breadth_cm < 'Infinity'::numeric)) AND
    (height_cm IS NULL OR (height_cm >= 0 AND height_cm < 'Infinity'::numeric))
  );

ALTER TABLE "listing_revisions"
  ADD CONSTRAINT "listing_revision_number_positive" CHECK (number > 0),
  ADD CONSTRAINT "listing_revision_snapshots_objects" CHECK (
    jsonb_typeof(merchant_snapshot) = 'object' AND
    jsonb_typeof(brand_context_snapshot) = 'object' AND
    jsonb_typeof(generation_metadata) = 'object' AND
    jsonb_typeof(aplus_content) = 'object' AND
    jsonb_typeof(target_keywords) = 'array'
  );

ALTER TABLE "marketplace_payloads"
  ADD CONSTRAINT "marketplace_payload_attributes_object" CHECK (jsonb_typeof(raw_attributes) = 'object');

ALTER TABLE "generation_jobs"
  ADD CONSTRAINT "generation_attempts_bounded" CHECK (max_attempts > 0 AND attempts >= 0 AND attempts <= max_attempts),
  ADD CONSTRAINT "generation_input_object" CHECK (jsonb_typeof(input_snapshot) = 'object'),
  ADD CONSTRAINT "generation_times_ordered" CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at);

ALTER TABLE "validation_runs"
  ADD CONSTRAINT "validation_score_range" CHECK (score IS NULL OR score BETWEEN 0 AND 100),
  ADD CONSTRAINT "validation_reports_arrays" CHECK (jsonb_typeof(errors) = 'array' AND jsonb_typeof(warnings) = 'array'),
  ADD CONSTRAINT "validation_pass_has_no_errors" CHECK (status <> 'PASSED' OR errors = '[]'::jsonb),
  ADD CONSTRAINT "validation_terminal_timestamp" CHECK ((status = 'PENDING') = (completed_at IS NULL));

ALTER TABLE "listing_approvals"
  ADD CONSTRAINT "approval_revocation_after_approval" CHECK (revoked_at IS NULL OR revoked_at >= approved_at);
CREATE UNIQUE INDEX "listing_approvals_one_active_per_revision"
  ON "listing_approvals" (revision_id) WHERE revoked_at IS NULL;

ALTER TABLE "publish_jobs"
  ADD CONSTRAINT "publish_attempts_nonnegative" CHECK (attempts >= 0),
  ADD CONSTRAINT "publish_idempotency_nonempty" CHECK (btrim(idempotency_key) <> ''),
  ADD CONSTRAINT "publish_target_object" CHECK (jsonb_typeof(target_snapshot) = 'object'),
  ADD CONSTRAINT "publish_route_connection" CHECK (route <> 'DIRECT_API' OR connection_id IS NOT NULL),
  ADD CONSTRAINT "publish_route_status_compatible" CHECK (
    (route = 'DIRECT_API' OR status NOT IN ('SUBMITTED', 'PUBLISHED')) AND
    (route = 'FLAT_FILE_CSV' OR status <> 'EXPORT_READY')
  ),
  ADD CONSTRAINT "publish_export_result_present" CHECK (
    status <> 'EXPORT_READY' OR (export_asset_id IS NOT NULL AND completed_at IS NOT NULL)
  ),
  ADD CONSTRAINT "publish_submission_result_present" CHECK (
    status NOT IN ('SUBMITTED', 'PUBLISHED') OR (submission_id IS NOT NULL AND submitted_at IS NOT NULL)
  ),
  ADD CONSTRAINT "publish_live_timestamp_present" CHECK (
    status <> 'PUBLISHED' OR (published_at IS NOT NULL AND completed_at IS NOT NULL)
  );

ALTER TABLE "media_assets" ADD CONSTRAINT "asset_size_nonnegative" CHECK (size_bytes >= 0);
ALTER TABLE "product_media" ADD CONSTRAINT "media_position_nonnegative" CHECK (position >= 0);
CREATE UNIQUE INDEX "product_media_parent_position_unique"
  ON "product_media" (product_id, position) WHERE variant_id IS NULL;
CREATE UNIQUE INDEX "product_media_variant_position_unique"
  ON "product_media" (variant_id, position) WHERE variant_id IS NOT NULL;
CREATE UNIQUE INDEX "product_media_parent_main_unique"
  ON "product_media" (product_id) WHERE variant_id IS NULL AND role = 'MAIN_IMAGE';
CREATE UNIQUE INDEX "product_media_variant_main_unique"
  ON "product_media" (variant_id) WHERE variant_id IS NOT NULL AND role = 'MAIN_IMAGE';

ALTER TABLE "import_batches"
  ADD CONSTRAINT "import_counts_valid" CHECK (
    total_rows >= 0 AND imported_rows >= 0 AND failed_rows >= 0 AND
    imported_rows::bigint + failed_rows::bigint <= total_rows::bigint
  ),
  ADD CONSTRAINT "import_completed_counts_valid" CHECK (
    status <> 'COMPLETED' OR (imported_rows::bigint + failed_rows::bigint = total_rows::bigint AND completed_at IS NOT NULL)
  ),
  ADD CONSTRAINT "import_errors_array" CHECK (jsonb_typeof(error_report) = 'array');

COMMIT;
